# Generated by Django 5.0 on 2024-02-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcode/')),
                ('attendance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qrapp.attendance')),
            ],
        ),
    ]
