# Generated by Django 5.0 on 2024-02-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_qrcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='attendance',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qrapp.course'),
        ),
    ]
